Avoid null pointer use if malloc() fails
Error: Null pointer dereference (CWE 476)
   Read from null pointer str
        at line 282 of handle.c in function 'parse_number'.
          Function copy_to_scratch may return constant 'NULL' at line 98,
           called at line 875 in function 'do_pointer'.
          Constant 'NULL' passed into function parse_number, argument str,
           from call at line 876.
          Null pointer introduced at line 98 in function 'copy_to_scratch'.

[ This bug was found by the Parfait 1.4.0 bug checking tool.
  http://labs.oracle.com/pls/apex/f?p=labs:49:::::P49_PROJECT_ID:13 ]

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>